---
title: "Cultural Values and Instrumental Variables - Codebook"
author: "Ronei Leonel"
output: 
  html_document:
    toc: true
    toc_depth: 4

---

[5-HTTLPR](#5HTTLPR)  
  
**N_Studies**: Number of studies that authors used to find % S allele  
**N**: Total Sample of studies  
**Percent S**: % of S(hort) allele  
**Perccent L**: % of L(ong) allele  

Source: Chiao, J. Y., & Blizinsky, K. D. (2010). Culture–gene coevolution of individualism–collectivism and the serotonin transporter gene. Proceedings of the Royal Society B: Biological Sciences, 277(1681), 529-537. [Appendix 1](https://royalsocietypublishing.org/action/downloadSupplement?doi=10.1098%2Frspb.2009.1650&file=rspb20091650supp4.pdf), [Appendix 2](https://royalsocietypublishing.org/action/downloadSupplement?doi=10.1098%2Frspb.2009.1650&file=rspb20091650supp1.doc)  

[Pronoun Drop](#language1)  

**1PS**: Number of First Personal Pronoun. 1 indicates multiples 1PS, 0 otherwise  
**2PS**: Number of Second Personal Pronoun. 1 indicates multiples 2PS, 0 otherwise  
**Pronoun drop**: it indicates if the language almost always requires a 1PS pronoun in an independent clause or not. 1 indicates that the pronoun drop is NOT allowed, zero other  
  
Source: Kashima, E. S., & Kashima, Y. (1998). Culture and Language. Journal of Cross-Cultural Psychology, 29(3), 461–486. doi:10.1177/0022022198293005

[Linguistic Fractionalization](#language2)  
  
**Linguistic Fractionalization**: The probability that two randomly selected individuals from a population belong to different linguistic.

Source: Alesina, A., Devleeschauwer, A., Easterly, W., Kurlat, S., & Wacziarg, R. (2003). Fractionalization. Journal of Economic growth, 8(2), 155-194.   
  
[Religion - Guiso 2003](#Religion1)  
  
**Catholic**: % of Catholic  
**Protestant**:  % of Protestant  
**Jewish**: % of Jewish  
**Muslim**: % of Muslim  
**Hindu**: % of Hindu  
**Buddhist**: % of Biddhist  
**Other affiliations**: % of Other affiliations  
**No religious affiliations**: % of No religious affiliations  

Source: Guiso, L., Sapienza, P., & Zingales, L. (2003). People's opium? Religion and economic attitudes. Journal of monetary economics, 50(1), 225-282.  

[Religion - La Porta 1999](#Religion2)  

**Catholic**: % of Catholic in 1980  
**Muslim**: % of Muslim in 1980  

Source: La Porta, R., Lopez-de-Silanes, F., Shleifer, A., & Vishny, R. (1999). The quality of government. The Journal of Law, Economics, and Organization, 15(1), 222-279.

[Unpaid parking tickets](#ticket)


[Ethic and religion Fractionalization](#fractionalization)  

**Source Ethnicity Data**: The source from the ethnicity data  
**Date Ethnicity Data**: The year for the ethnicity data  
**Ethnic Fractionalization**: The probability that two randomly selected individuals from a population belong to different ethnic   
**Religion Fractionalization**: The probability that two randomly selected individuals from a population belong to different religion   
Note: eb = Encyclopedia Brittanica, cia = CIA, sm = Scarrit and Mozaffar; lev = Levinson; wdm = World Directory of Minorities; census = national census data   
  
Source: Alesina, A., Devleeschauwer, A., Easterly, W., Kurlat, S., & Wacziarg, R. (2003). Fractionalization. Journal of Economic growth, 8(2), 155-194.   

[Latitude](#latitude)  

**Latitude**: the absolute value of latitude in degrees divided by 90 to place it on a 0 to 1 scale. The latitude of each country was obtained from the Global Demography Project at U.C. Santa Barbara (http://www.ciesin.org/datasets/gpw/globldem.doc.html), discussed by Tobler, Deichmann, Gottsegen and Maloy (1995). These location data correspond to the center of the county or province within a country that contains the largest number of people  
  
Source: Hall, R. E., & Jones, C. I. (1999). Why do some countries produce so much more output per worker than others?. The quarterly journal of economics, 114(1), 83-116.  

[Temperature](#Temperature)  

**Temperature**: Average daytime temperature of the country’s capital city 
  
Source: Hall, R. E., & Jones, C. I. (1999). Why do some countries produce so much more output per worker than others?. The quarterly journal of economics, 114(1), 83-116. 

